/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    stm32f0xx_it.c
  * @brief   Interrupt Service Routines.
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/**
 *******************************************************************************
 * Flight simulator avionics controller interrupt service routines
 *******************************************************************************
 * Code in this file was generated by STM32CubeIDE with USER CODE sections
 * contributed by Tyler A Stank.
 * This contains the interrupt service routines for the application described in
 * main.c, including the "main loop" which is triggered by a 1ms interrupt from
 * TIM7.
 *******************************************************************************
 */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "stm32f0xx_it.h"
/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "usb_device.h"
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN TD */

/* USER CODE END TD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
/* USER CODE BEGIN PV */
uint8_t mode = 0;
uint16_t encoder_1_pos = 0;
uint16_t encoder_2_pos = 0;
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/* External variables --------------------------------------------------------*/
extern PCD_HandleTypeDef hpcd_USB_FS;
extern TIM_HandleTypeDef htim7;
/* USER CODE BEGIN EV */

/* USER CODE END EV */

/******************************************************************************/
/*           Cortex-M0 Processor Interruption and Exception Handlers          */
/******************************************************************************/
/**
  * @brief This function handles Non maskable interrupt.
  */
void NMI_Handler(void)
{
  /* USER CODE BEGIN NonMaskableInt_IRQn 0 */

  /* USER CODE END NonMaskableInt_IRQn 0 */
  /* USER CODE BEGIN NonMaskableInt_IRQn 1 */
   while (1)
  {
  }
  /* USER CODE END NonMaskableInt_IRQn 1 */
}

/**
  * @brief This function handles Hard fault interrupt.
  */
void HardFault_Handler(void)
{
  /* USER CODE BEGIN HardFault_IRQn 0 */

  /* USER CODE END HardFault_IRQn 0 */
  while (1)
  {
    /* USER CODE BEGIN W1_HardFault_IRQn 0 */
    /* USER CODE END W1_HardFault_IRQn 0 */
  }
}

/**
  * @brief This function handles System service call via SWI instruction.
  */
void SVC_Handler(void)
{
  /* USER CODE BEGIN SVC_IRQn 0 */

  /* USER CODE END SVC_IRQn 0 */
  /* USER CODE BEGIN SVC_IRQn 1 */

  /* USER CODE END SVC_IRQn 1 */
}

/**
  * @brief This function handles Pendable request for system service.
  */
void PendSV_Handler(void)
{
  /* USER CODE BEGIN PendSV_IRQn 0 */

  /* USER CODE END PendSV_IRQn 0 */
  /* USER CODE BEGIN PendSV_IRQn 1 */

  /* USER CODE END PendSV_IRQn 1 */
}

/**
  * @brief This function handles System tick timer.
  */
void SysTick_Handler(void)
{
  /* USER CODE BEGIN SysTick_IRQn 0 */

  /* USER CODE END SysTick_IRQn 0 */
  HAL_IncTick();
  /* USER CODE BEGIN SysTick_IRQn 1 */

  /* USER CODE END SysTick_IRQn 1 */
}

/******************************************************************************/
/* STM32F0xx Peripheral Interrupt Handlers                                    */
/* Add here the Interrupt Handlers for the used peripherals.                  */
/* For the available peripheral interrupt handler names,                      */
/* please refer to the startup file (startup_stm32f0xx.s).                    */
/******************************************************************************/

/**
  * @brief This function handles TIM7 global interrupt.
  */
void TIM7_IRQHandler(void)
{
  /* USER CODE BEGIN TIM7_IRQn 0 */
  for (int i = 0; i < BUTTON_STATE_SIZE; i++) {
    button_state[i] = 0x00;
  }
  /* USER CODE END TIM7_IRQn 0 */
  HAL_TIM_IRQHandler(&htim7);
  /* USER CODE BEGIN TIM7_IRQn 1 */
  for (int i = 0; i < MODE_BUTTON_COUNT; i++) {
    // this will have the effect of switching between the first two in sequence if two or more buttons are held;
    // that's not something the user should expect to have a meaningful result, so I'm not going to care about it.
    if (HAL_GPIO_ReadPin(mode_button_ports[i], mode_button_pins[i]) == GPIO_PIN_RESET && mode != i) {
      HAL_GPIO_WritePin(mode_led_ports[mode], mode_led_pins[mode], GPIO_PIN_RESET);
      mode = i;
      HAL_GPIO_WritePin(mode_led_ports[mode], mode_led_pins[mode], GPIO_PIN_SET);
      break;
    }
  }
  // poll the rest of the buttons and send their state directly to the sim
  // TODO ensure no software debouncing is necessary
  for (int i = 0; i < DIRECT_SEND_BUTTON_COUNT; i++) {
    if (HAL_GPIO_ReadPin(direct_send_button_ports[i], direct_send_button_pins[i]) == GPIO_PIN_RESET) {
      set_bit(button_state, i);
    }
  }

  int16_t encoder_1_difference = (uint16_t)TIM1->CNT - encoder_1_pos;
  int16_t encoder_2_difference = (uint16_t)TIM3->CNT - encoder_2_pos;
  uint8_t encoder_logical_button_base = DIRECT_SEND_BUTTON_COUNT + mode * ENCODER_STATES_COUNT;
  // the timer increments twice per detent, so only send a button press if it has changed by more than one.
  if (encoder_1_difference > 1) {
    set_bit(button_state, encoder_logical_button_base + ENCODER_1_UP);
    encoder_1_pos = TIM1->CNT;
  } else if (encoder_1_difference < -1) {
    set_bit(button_state, encoder_logical_button_base + ENCODER_1_DOWN);
    encoder_1_pos = TIM1->CNT;
  }
  if (encoder_2_difference > 1) {
    set_bit(button_state, encoder_logical_button_base + ENCODER_2_UP);
    encoder_2_pos = TIM3->CNT;
  } else if (encoder_2_difference < -1) {
    set_bit(button_state, encoder_logical_button_base + ENCODER_2_DOWN);
    encoder_2_pos = TIM3->CNT;
  }

  //send USB report
  send_hid_report(button_state, BUTTON_STATE_SIZE);
  /* USER CODE END TIM7_IRQn 1 */
}

/**
  * @brief This function handles USB global interrupt / USB wake-up interrupt through EXTI line 18.
  */
void USB_IRQHandler(void)
{
  /* USER CODE BEGIN USB_IRQn 0 */

  /* USER CODE END USB_IRQn 0 */
  HAL_PCD_IRQHandler(&hpcd_USB_FS);
  /* USER CODE BEGIN USB_IRQn 1 */

  /* USER CODE END USB_IRQn 1 */
}

/* USER CODE BEGIN 1 */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin) {

}
/* USER CODE END 1 */
